package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HisAtenciones generated by hbm2java
 */
@Entity
@Table(name = "his_atenciones")
public class HisAtenciones implements java.io.Serializable {

	private String idCita;
	private HisMaestroPersonal hisMaestroPersonal;
	private MIpress MIpress;
	private MMes MMes;
	private MSexo MSexo;
	private MTurnoAtencion MTurnoAtencion;
	private MUbigeo MUbigeo;
	private String idAtencion;
	private String anio;
	private String dia;
	private String lote;
	private String numPag;
	private String numReg;
	private String servicio;
	private String tipoDoc;
	private String identificador;
	private String nroDoc;
	private String fechaNac;
	private String nroHcl;
	private String fichafam;
	private String financiador;
	private String nroAfiliacion;
	private String condEess;
	private String condServ;
	private String tipoEdad;
	private String edadPacAnio;
	private String edadPacMes;
	private String edadPacDia;
	private Short edad;
	private String etnia;
	private String numDocRegistra;
	private String fechaRegistro;
	private String ultModificacion;
	private Date fecha;
	private Set<HisAtencionesDetalles> hisAtencionesDetalleses = new HashSet<HisAtencionesDetalles>(0);

	public HisAtenciones() {
	}

	public HisAtenciones(String idCita) {
		this.idCita = idCita;
	}

	public HisAtenciones(String idCita, HisMaestroPersonal hisMaestroPersonal, MIpress MIpress, MMes MMes, MSexo MSexo,
			MTurnoAtencion MTurnoAtencion, MUbigeo MUbigeo, String idAtencion, String anio, String dia, String lote,
			String numPag, String numReg, String servicio, String tipoDoc, String identificador, String nroDoc,
			String fechaNac, String nroHcl, String fichafam, String financiador, String nroAfiliacion, String condEess,
			String condServ, String tipoEdad, String edadPacAnio, String edadPacMes, String edadPacDia, Short edad,
			String etnia, String numDocRegistra, String fechaRegistro, String ultModificacion, Date fecha,
			Set<HisAtencionesDetalles> hisAtencionesDetalleses) {
		this.idCita = idCita;
		this.hisMaestroPersonal = hisMaestroPersonal;
		this.MIpress = MIpress;
		this.MMes = MMes;
		this.MSexo = MSexo;
		this.MTurnoAtencion = MTurnoAtencion;
		this.MUbigeo = MUbigeo;
		this.idAtencion = idAtencion;
		this.anio = anio;
		this.dia = dia;
		this.lote = lote;
		this.numPag = numPag;
		this.numReg = numReg;
		this.servicio = servicio;
		this.tipoDoc = tipoDoc;
		this.identificador = identificador;
		this.nroDoc = nroDoc;
		this.fechaNac = fechaNac;
		this.nroHcl = nroHcl;
		this.fichafam = fichafam;
		this.financiador = financiador;
		this.nroAfiliacion = nroAfiliacion;
		this.condEess = condEess;
		this.condServ = condServ;
		this.tipoEdad = tipoEdad;
		this.edadPacAnio = edadPacAnio;
		this.edadPacMes = edadPacMes;
		this.edadPacDia = edadPacDia;
		this.edad = edad;
		this.etnia = etnia;
		this.numDocRegistra = numDocRegistra;
		this.fechaRegistro = fechaRegistro;
		this.ultModificacion = ultModificacion;
		this.fecha = fecha;
		this.hisAtencionesDetalleses = hisAtencionesDetalleses;
	}

	@Id

	@Column(name = "id_cita", unique = true, nullable = false, length = 18)
	public String getIdCita() {
		return this.idCita;
	}

	public void setIdCita(String idCita) {
		this.idCita = idCita;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "num_doc_atiende")
	public HisMaestroPersonal getHisMaestroPersonal() {
		return this.hisMaestroPersonal;
	}

	public void setHisMaestroPersonal(HisMaestroPersonal hisMaestroPersonal) {
		this.hisMaestroPersonal = hisMaestroPersonal;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "renaes")
	public MIpress getMIpress() {
		return this.MIpress;
	}

	public void setMIpress(MIpress MIpress) {
		this.MIpress = MIpress;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mes")
	public MMes getMMes() {
		return this.MMes;
	}

	public void setMMes(MMes MMes) {
		this.MMes = MMes;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genero")
	public MSexo getMSexo() {
		return this.MSexo;
	}

	public void setMSexo(MSexo MSexo) {
		this.MSexo = MSexo;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "turno_atencion")
	public MTurnoAtencion getMTurnoAtencion() {
		return this.MTurnoAtencion;
	}

	public void setMTurnoAtencion(MTurnoAtencion MTurnoAtencion) {
		this.MTurnoAtencion = MTurnoAtencion;
	}
	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ubigeo")
	public MUbigeo getMUbigeo() {
		return this.MUbigeo;
	}

	public void setMUbigeo(MUbigeo MUbigeo) {
		this.MUbigeo = MUbigeo;
	}

	@Column(name = "id_atencion", length = 33)
	public String getIdAtencion() {
		return this.idAtencion;
	}

	public void setIdAtencion(String idAtencion) {
		this.idAtencion = idAtencion;
	}

	@Column(name = "anio", length = 4)
	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	@Column(name = "dia", length = 2)
	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	@Column(name = "lote", length = 3)
	public String getLote() {
		return this.lote;
	}

	public void setLote(String lote) {
		this.lote = lote;
	}

	@Column(name = "num_pag", length = 3)
	public String getNumPag() {
		return this.numPag;
	}

	public void setNumPag(String numPag) {
		this.numPag = numPag;
	}

	@Column(name = "num_reg", length = 3)
	public String getNumReg() {
		return this.numReg;
	}

	public void setNumReg(String numReg) {
		this.numReg = numReg;
	}

	@Column(name = "servicio", length = 6)
	public String getServicio() {
		return this.servicio;
	}

	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	@Column(name = "tipo_doc", length = 12)
	public String getTipoDoc() {
		return this.tipoDoc;
	}

	public void setTipoDoc(String tipoDoc) {
		this.tipoDoc = tipoDoc;
	}

	@Column(name = "identificador", length = 20)
	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	@Column(name = "nro_doc", length = 15)
	public String getNroDoc() {
		return this.nroDoc;
	}

	public void setNroDoc(String nroDoc) {
		this.nroDoc = nroDoc;
	}

	@Column(name = "fecha_nac", length = 12)
	public String getFechaNac() {
		return this.fechaNac;
	}

	public void setFechaNac(String fechaNac) {
		this.fechaNac = fechaNac;
	}

	@Column(name = "nro_hcl", length = 20)
	public String getNroHcl() {
		return this.nroHcl;
	}

	public void setNroHcl(String nroHcl) {
		this.nroHcl = nroHcl;
	}

	@Column(name = "fichafam", length = 12)
	public String getFichafam() {
		return this.fichafam;
	}

	public void setFichafam(String fichafam) {
		this.fichafam = fichafam;
	}

	@Column(name = "financiador", length = 20)
	public String getFinanciador() {
		return this.financiador;
	}

	public void setFinanciador(String financiador) {
		this.financiador = financiador;
	}

	@Column(name = "nro_afiliacion", length = 20)
	public String getNroAfiliacion() {
		return this.nroAfiliacion;
	}

	public void setNroAfiliacion(String nroAfiliacion) {
		this.nroAfiliacion = nroAfiliacion;
	}

	@Column(name = "cond_eess", length = 1)
	public String getCondEess() {
		return this.condEess;
	}

	public void setCondEess(String condEess) {
		this.condEess = condEess;
	}

	@Column(name = "cond_serv", length = 1)
	public String getCondServ() {
		return this.condServ;
	}

	public void setCondServ(String condServ) {
		this.condServ = condServ;
	}

	@Column(name = "tipo_edad", length = 3)
	public String getTipoEdad() {
		return this.tipoEdad;
	}

	public void setTipoEdad(String tipoEdad) {
		this.tipoEdad = tipoEdad;
	}

	@Column(name = "edad_pac_anio", length = 3)
	public String getEdadPacAnio() {
		return this.edadPacAnio;
	}

	public void setEdadPacAnio(String edadPacAnio) {
		this.edadPacAnio = edadPacAnio;
	}

	@Column(name = "edad_pac_mes", length = 2)
	public String getEdadPacMes() {
		return this.edadPacMes;
	}

	public void setEdadPacMes(String edadPacMes) {
		this.edadPacMes = edadPacMes;
	}

	@Column(name = "edad_pac_dia", length = 2)
	public String getEdadPacDia() {
		return this.edadPacDia;
	}

	public void setEdadPacDia(String edadPacDia) {
		this.edadPacDia = edadPacDia;
	}

	@Column(name = "edad")
	public Short getEdad() {
		return this.edad;
	}

	public void setEdad(Short edad) {
		this.edad = edad;
	}

	@Column(name = "etnia", length = 3)
	public String getEtnia() {
		return this.etnia;
	}

	public void setEtnia(String etnia) {
		this.etnia = etnia;
	}

	@Column(name = "num_doc_registra", length = 8)
	public String getNumDocRegistra() {
		return this.numDocRegistra;
	}

	public void setNumDocRegistra(String numDocRegistra) {
		this.numDocRegistra = numDocRegistra;
	}

	@Column(name = "fecha_registro", length = 12)
	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "ult_modificacion", length = 12)
	public String getUltModificacion() {
		return this.ultModificacion;
	}

	public void setUltModificacion(String ultModificacion) {
		this.ultModificacion = ultModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hisAtenciones")
	public Set<HisAtencionesDetalles> getHisAtencionesDetalleses() {
		return this.hisAtencionesDetalleses;
	}

	public void setHisAtencionesDetalleses(Set<HisAtencionesDetalles> hisAtencionesDetalleses) {
		this.hisAtencionesDetalleses = hisAtencionesDetalleses;
	}

}
