package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MFinanciador generated by hbm2java
 */
@Entity
@Table(name = "m_financiador")
public class MFinanciador implements java.io.Serializable {

	private String tipoFinanciador;
	private Integer id;

	public MFinanciador() {
	}

	public MFinanciador(String tipoFinanciador) {
		this.tipoFinanciador = tipoFinanciador;
	}

	public MFinanciador(String tipoFinanciador, Integer id) {
		this.tipoFinanciador = tipoFinanciador;
		this.id = id;
	}

	@Id

	@Column(name = "tipo_financiador", unique = true, nullable = false, length = 20)
	public String getTipoFinanciador() {
		return this.tipoFinanciador;
	}

	public void setTipoFinanciador(String tipoFinanciador) {
		this.tipoFinanciador = tipoFinanciador;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
