package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MIpress generated by hbm2java
 */
@Entity
@Table(name = "m_ipress")
public class MIpress implements java.io.Serializable {

	private String codigoUnico;
	private String institucion;
	private String nombreEstablecimiento;
	private String clasificacion;
	private String tipo;
	private String departamento;
	private String provincia;
	private String distrito;
	private String ubigeo;
	private String direccion;
	private String codigoDisa;
	private String codigoRed;
	private String codigoMicrorred;
	private String disa;
	private String red;
	private String microrred;
	private String codigoUe;
	private String unidadEjecutora;
	private String categoria;
	private String telefono;
	private String tipoDocCategorizacion;
	private String nroDocCategorizacion;
	private String horario;
	private String inicioActividad;
	private String directorMedicoResponsableAtencionSalud;
	private String estado;
	private String situacion;
	private String condicion;
	private String inspeccion;
	private String norte;
	private String este;
	private String cota;
	private String camas;
	private Set<HisAtenciones> hisAtencioneses = new HashSet<HisAtenciones>(0);

	public MIpress() {
	}

	public MIpress(String codigoUnico) {
		this.codigoUnico = codigoUnico;
	}

	public MIpress(String codigoUnico, String institucion, String nombreEstablecimiento, String clasificacion,
			String tipo, String departamento, String provincia, String distrito, String ubigeo, String direccion,
			String codigoDisa, String codigoRed, String codigoMicrorred, String disa, String red, String microrred,
			String codigoUe, String unidadEjecutora, String categoria, String telefono, String tipoDocCategorizacion,
			String nroDocCategorizacion, String horario, String inicioActividad,
			String directorMedicoResponsableAtencionSalud, String estado, String situacion, String condicion,
			String inspeccion, String norte, String este, String cota, String camas,
			Set<HisAtenciones> hisAtencioneses) {
		this.codigoUnico = codigoUnico;
		this.institucion = institucion;
		this.nombreEstablecimiento = nombreEstablecimiento;
		this.clasificacion = clasificacion;
		this.tipo = tipo;
		this.departamento = departamento;
		this.provincia = provincia;
		this.distrito = distrito;
		this.ubigeo = ubigeo;
		this.direccion = direccion;
		this.codigoDisa = codigoDisa;
		this.codigoRed = codigoRed;
		this.codigoMicrorred = codigoMicrorred;
		this.disa = disa;
		this.red = red;
		this.microrred = microrred;
		this.codigoUe = codigoUe;
		this.unidadEjecutora = unidadEjecutora;
		this.categoria = categoria;
		this.telefono = telefono;
		this.tipoDocCategorizacion = tipoDocCategorizacion;
		this.nroDocCategorizacion = nroDocCategorizacion;
		this.horario = horario;
		this.inicioActividad = inicioActividad;
		this.directorMedicoResponsableAtencionSalud = directorMedicoResponsableAtencionSalud;
		this.estado = estado;
		this.situacion = situacion;
		this.condicion = condicion;
		this.inspeccion = inspeccion;
		this.norte = norte;
		this.este = este;
		this.cota = cota;
		this.camas = camas;
		this.hisAtencioneses = hisAtencioneses;
	}

	@Id

	@Column(name = "codigo_unico", unique = true, nullable = false, length = 8)
	public String getCodigoUnico() {
		return this.codigoUnico;
	}

	public void setCodigoUnico(String codigoUnico) {
		this.codigoUnico = codigoUnico;
	}

	@Column(name = "institucion", length = 250)
	public String getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}

	@Column(name = "nombre_establecimiento", length = 250)
	public String getNombreEstablecimiento() {
		return this.nombreEstablecimiento;
	}

	public void setNombreEstablecimiento(String nombreEstablecimiento) {
		this.nombreEstablecimiento = nombreEstablecimiento;
	}

	@Column(name = "clasificacion", length = 250)
	public String getClasificacion() {
		return this.clasificacion;
	}

	public void setClasificacion(String clasificacion) {
		this.clasificacion = clasificacion;
	}

	@Column(name = "tipo", length = 250)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "departamento", length = 250)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "provincia", length = 100)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "distrito", length = 100)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "ubigeo", length = 80)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "direccion", length = 250)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "codigo_disa", length = 6)
	public String getCodigoDisa() {
		return this.codigoDisa;
	}

	public void setCodigoDisa(String codigoDisa) {
		this.codigoDisa = codigoDisa;
	}

	@Column(name = "codigo_red", length = 6)
	public String getCodigoRed() {
		return this.codigoRed;
	}

	public void setCodigoRed(String codigoRed) {
		this.codigoRed = codigoRed;
	}

	@Column(name = "codigo_microrred", length = 6)
	public String getCodigoMicrorred() {
		return this.codigoMicrorred;
	}

	public void setCodigoMicrorred(String codigoMicrorred) {
		this.codigoMicrorred = codigoMicrorred;
	}

	@Column(name = "disa", length = 100)
	public String getDisa() {
		return this.disa;
	}

	public void setDisa(String disa) {
		this.disa = disa;
	}

	@Column(name = "red", length = 100)
	public String getRed() {
		return this.red;
	}

	public void setRed(String red) {
		this.red = red;
	}

	@Column(name = "microrred", length = 100)
	public String getMicrorred() {
		return this.microrred;
	}

	public void setMicrorred(String microrred) {
		this.microrred = microrred;
	}

	@Column(name = "codigo_ue")
	public String getCodigoUe() {
		return this.codigoUe;
	}

	public void setCodigoUe(String codigoUe) {
		this.codigoUe = codigoUe;
	}

	@Column(name = "unidad_ejecutora")
	public String getUnidadEjecutora() {
		return this.unidadEjecutora;
	}

	public void setUnidadEjecutora(String unidadEjecutora) {
		this.unidadEjecutora = unidadEjecutora;
	}

	@Column(name = "categoria")
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "telefono")
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "tipo_doc_categorizacion")
	public String getTipoDocCategorizacion() {
		return this.tipoDocCategorizacion;
	}

	public void setTipoDocCategorizacion(String tipoDocCategorizacion) {
		this.tipoDocCategorizacion = tipoDocCategorizacion;
	}

	@Column(name = "nro_doc_categorizacion")
	public String getNroDocCategorizacion() {
		return this.nroDocCategorizacion;
	}

	public void setNroDocCategorizacion(String nroDocCategorizacion) {
		this.nroDocCategorizacion = nroDocCategorizacion;
	}

	@Column(name = "horario")
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@Column(name = "inicio_actividad")
	public String getInicioActividad() {
		return this.inicioActividad;
	}

	public void setInicioActividad(String inicioActividad) {
		this.inicioActividad = inicioActividad;
	}

	@Column(name = "director_medico_responsable_atencion_salud", length = 10)
	public String getDirectorMedicoResponsableAtencionSalud() {
		return this.directorMedicoResponsableAtencionSalud;
	}

	public void setDirectorMedicoResponsableAtencionSalud(String directorMedicoResponsableAtencionSalud) {
		this.directorMedicoResponsableAtencionSalud = directorMedicoResponsableAtencionSalud;
	}

	@Column(name = "estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "situacion")
	public String getSituacion() {
		return this.situacion;
	}

	public void setSituacion(String situacion) {
		this.situacion = situacion;
	}

	@Column(name = "condicion", length = 50)
	public String getCondicion() {
		return this.condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	@Column(name = "inspeccion")
	public String getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(String inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "norte", length = 20)
	public String getNorte() {
		return this.norte;
	}

	public void setNorte(String norte) {
		this.norte = norte;
	}

	@Column(name = "este", length = 20)
	public String getEste() {
		return this.este;
	}

	public void setEste(String este) {
		this.este = este;
	}

	@Column(name = "cota", length = 4)
	public String getCota() {
		return this.cota;
	}

	public void setCota(String cota) {
		this.cota = cota;
	}

	@Column(name = "camas", length = 4)
	public String getCamas() {
		return this.camas;
	}

	public void setCamas(String camas) {
		this.camas = camas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MIpress")
	public Set<HisAtenciones> getHisAtencioneses() {
		return this.hisAtencioneses;
	}

	public void setHisAtencioneses(Set<HisAtenciones> hisAtencioneses) {
		this.hisAtencioneses = hisAtencioneses;
	}

}
