package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MMes generated by hbm2java
 */
@Entity
@Table(name = "m_mes")
public class MMes implements java.io.Serializable {

	private String idMes;
	private String nombre;
	private Set<HisAtenciones> hisAtencioneses = new HashSet<HisAtenciones>(0);

	public MMes() {
	}

	public MMes(String idMes) {
		this.idMes = idMes;
	}

	public MMes(String idMes, String nombre, Set<HisAtenciones> hisAtencioneses) {
		this.idMes = idMes;
		this.nombre = nombre;
		this.hisAtencioneses = hisAtencioneses;
	}

	@Id

	@Column(name = "id_mes", unique = true, nullable = false, length = 2)
	public String getIdMes() {
		return this.idMes;
	}

	public void setIdMes(String idMes) {
		this.idMes = idMes;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MMes")
	public Set<HisAtenciones> getHisAtencioneses() {
		return this.hisAtencioneses;
	}

	public void setHisAtencioneses(Set<HisAtenciones> hisAtencioneses) {
		this.hisAtencioneses = hisAtencioneses;
	}

}
