package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MPaciente generated by hbm2java
 */
@Entity
@Table(name = "m_paciente")
public class MPaciente implements java.io.Serializable {

	private String dni;
	private String nombres;

	public MPaciente() {
	}

	public MPaciente(String dni) {
		this.dni = dni;
	}

	public MPaciente(String dni, String nombres) {
		this.dni = dni;
		this.nombres = nombres;
	}

	@Id

	@Column(name = "dni", unique = true, nullable = false, length = 15)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nombres", length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

}
