package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MSexo generated by hbm2java
 */
@Entity
@Table(name = "m_sexo")
public class MSexo implements java.io.Serializable {

	private String codSexo;
	private String descSexo;
	private Set<HisAtenciones> hisAtencioneses = new HashSet<HisAtenciones>(0);

	public MSexo() {
	}

	public MSexo(String codSexo) {
		this.codSexo = codSexo;
	}

	public MSexo(String codSexo, String descSexo, Set<HisAtenciones> hisAtencioneses) {
		this.codSexo = codSexo;
		this.descSexo = descSexo;
		this.hisAtencioneses = hisAtencioneses;
	}

	@Id

	@Column(name = "cod_sexo", unique = true, nullable = false, length = 1)
	public String getCodSexo() {
		return this.codSexo;
	}

	public void setCodSexo(String codSexo) {
		this.codSexo = codSexo;
	}

	@Column(name = "desc_sexo", length = 15)
	public String getDescSexo() {
		return this.descSexo;
	}

	public void setDescSexo(String descSexo) {
		this.descSexo = descSexo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MSexo")
	public Set<HisAtenciones> getHisAtencioneses() {
		return this.hisAtencioneses;
	}

	public void setHisAtencioneses(Set<HisAtenciones> hisAtencioneses) {
		this.hisAtencioneses = hisAtencioneses;
	}

}
