package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MUbigeo generated by hbm2java
 */
@Entity
@Table(name = "m_ubigeo")
public class MUbigeo implements java.io.Serializable {

	private String idUbigeo;
	private String departamento;
	private String provincia;
	private String distrito;
	private Set<HisAtenciones> hisAtencioneses = new HashSet<HisAtenciones>(0);

	public MUbigeo() {
	}

	public MUbigeo(String idUbigeo) {
		this.idUbigeo = idUbigeo;
	}

	public MUbigeo(String idUbigeo, String departamento, String provincia, String distrito,
			Set<HisAtenciones> hisAtencioneses) {
		this.idUbigeo = idUbigeo;
		this.departamento = departamento;
		this.provincia = provincia;
		this.distrito = distrito;
		this.hisAtencioneses = hisAtencioneses;
	}

	@Id

	@Column(name = "id_ubigeo", unique = true, nullable = false, length = 6)
	public String getIdUbigeo() {
		return this.idUbigeo;
	}

	public void setIdUbigeo(String idUbigeo) {
		this.idUbigeo = idUbigeo;
	}

	@Column(name = "departamento", length = 13)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "provincia", length = 25)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "distrito", length = 30)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MUbigeo")
	public Set<HisAtenciones> getHisAtencioneses() {
		return this.hisAtencioneses;
	}

	public void setHisAtencioneses(Set<HisAtenciones> hisAtencioneses) {
		this.hisAtencioneses = hisAtencioneses;
	}

}
