package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tiempo generated by hbm2java
 */
@Entity
@Table(name = "tiempo")
public class Tiempo implements java.io.Serializable {

	private int tiempoKey;
	private Date fecha;
	private Integer dia;
	private Integer mes;
	private Integer semestre;
	private Integer anio;
	private Integer diaSemana;
	private Integer semanaDelAnio;
	private String mesNombre;
	private String semestreNombre;
	private String diaSemanaNombre;

	public Tiempo() {
	}

	public Tiempo(int tiempoKey) {
		this.tiempoKey = tiempoKey;
	}

	public Tiempo(int tiempoKey, Date fecha, Integer dia, Integer mes, Integer semestre, Integer anio,
			Integer diaSemana, Integer semanaDelAnio, String mesNombre, String semestreNombre, String diaSemanaNombre) {
		this.tiempoKey = tiempoKey;
		this.fecha = fecha;
		this.dia = dia;
		this.mes = mes;
		this.semestre = semestre;
		this.anio = anio;
		this.diaSemana = diaSemana;
		this.semanaDelAnio = semanaDelAnio;
		this.mesNombre = mesNombre;
		this.semestreNombre = semestreNombre;
		this.diaSemanaNombre = diaSemanaNombre;
	}

	@Id

	@Column(name = "tiempo_key", unique = true, nullable = false)
	public int getTiempoKey() {
		return this.tiempoKey;
	}

	public void setTiempoKey(int tiempoKey) {
		this.tiempoKey = tiempoKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 23)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "dia")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "semestre")
	public Integer getSemestre() {
		return this.semestre;
	}

	public void setSemestre(Integer semestre) {
		this.semestre = semestre;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "dia_semana")
	public Integer getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(Integer diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Column(name = "semana_del_anio")
	public Integer getSemanaDelAnio() {
		return this.semanaDelAnio;
	}

	public void setSemanaDelAnio(Integer semanaDelAnio) {
		this.semanaDelAnio = semanaDelAnio;
	}

	@Column(name = "mes_nombre", length = 20)
	public String getMesNombre() {
		return this.mesNombre;
	}

	public void setMesNombre(String mesNombre) {
		this.mesNombre = mesNombre;
	}

	@Column(name = "semestre_nombre", length = 2)
	public String getSemestreNombre() {
		return this.semestreNombre;
	}

	public void setSemestreNombre(String semestreNombre) {
		this.semestreNombre = semestreNombre;
	}

	@Column(name = "dia_semana_nombre", length = 10)
	public String getDiaSemanaNombre() {
		return this.diaSemanaNombre;
	}

	public void setDiaSemanaNombre(String diaSemanaNombre) {
		this.diaSemanaNombre = diaSemanaNombre;
	}

}
