package com.his.model;
// Generated 12/03/2020 10:16:04 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoDoc generated by hbm2java
 */
@Entity
@Table(name = "tipo_doc")
public class TipoDoc implements java.io.Serializable {

	private String nombre;
	private int idTipDoc;

	public TipoDoc() {
	}

	public TipoDoc(String nombre, int idTipDoc) {
		this.nombre = nombre;
		this.idTipDoc = idTipDoc;
	}

	@Id

	@Column(name = "nombre", unique = true, nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_tip_doc", nullable = false)
	public int getIdTipDoc() {
		return this.idTipDoc;
	}

	public void setIdTipDoc(int idTipDoc) {
		this.idTipDoc = idTipDoc;
	}

}
